config/routes.rb
Rails.application.routes.draw do


  get 'dashboard/index'

  get 'dashboard/inbox'

  get 'dashboard/orders'

  get 'dashboard/users'

  get 'dashboard/settings'

  get 'dashboard/analytics'

  devise_for :users
  
  get '/'                                               =>  "static#index"
  get '/about'                                          =>  "static#about"
  get '/contact'                                        =>  "static#contact"
  get '/faq'                                            =>  "static#faq"
  get '/privacy'                                        =>  "static#privacy"
  get '/legal-statement'                                =>  "static#legal"
  get '/terms-and-conditions'                           =>  "static#terms"
  get '/distributors'                                   =>  "static#distributors"

  get '/cart'                                           =>  "cart#index"
  post 'cart/add'                                       =>  "cart#add"
  get '/products/checkout'                                    =>  "cart#cart-2"
  post '/products/checkout'                             =>  "cart#cart"
  post '/checkout'                                      => 'cart#checkout'
  post '/execute'                                        =>  'cart#execute'
  get '/blog'                                           =>  "blog#index"
  get '/blog/5-reasons-why-invest-your-money-in-invisible-teeth-straightening'                                        =>  "blog#5-reason-blog"
  get '/blog/veneers-vswhite-bleaching'                 =>  "blog#veners-vs-white"
  get '/blog/Clear-braces-VS-metal-braces'              =>  "blog#clear-vs-metal"
  get '/blog/What-to-eat-after-veneers'                 =>  "blog#what-to-eat-after-veneers"

  get '/products'                                       =>  "static#products"
  get '/products/snapup'                                =>  "static#snapup"
  get '/products/snapup/customize'                      =>  "static#snapup_order"
  
  delete '/products/item/:id'                          ,to: "cart#remove_item", as: 'delete_item'
  get '/products/clearup'                               =>  "static#clearup"
  post '/products/address'                              => "cart#address"
  post '/products/sofort'                               => "cart#sofort_pay"
  get '/sofort_check'                                   => "cart#sofort_check"
  get 'products/clearup/candidate'                      =>  "clearup#candidate"
  post 'products/clearup/candidate'                      =>  "clearup#upload"

  get 'products/clearup/confirm'                      =>  "clearup#confirm"

  get 'products/clearup/clearup_impression'             => "static#clearup_impression"

  get 'products/clearup/clearup_shop'                   => "static#clearup_shop"
  resources :conversations
  get 'inbox' => 'conversations#inbox'
  get 'my_orders' => 'orders#my_orders'
end

app/controllers/cart_controller.rb
require 'paypal-sdk-rest'
include PayPal::SDK::REST
include PayPal::SDK::Core::Logging

class CartController < ApplicationController
    before_action :authenticate_user! , only: [:cart , :index]
    skip_before_action :verify_authenticity_token
  def index
    if current_user.nil?
      @currency = 'usd'
    else
      @currency = current_user.currency
    end
    @cart = session[:cart]
    @total = 0
    @cart.each do |ci|
      price = Product.find_by(name: ci['product']).product_prices.find_by(:currency => @currency).price
      quantity = ci['quantity'].to_i
      @total += (price * quantity)
    end
    @active = "cart"
    session[:total] = @total
    @total
  end

  def add
    previous_quantity = 0
    cart = session[:cart]
    previous = session[:cart]
    previous = previous.select {|ci| ci['product'] == params[:product]}
    previous = previous.select {|ci| ci['style'] == params[:style]}
    if previous.count == 1
      previous_quantity = previous[0]['quantity']
    end
    new_quantity = previous_quantity.to_i + params[:quantity].to_i
    cart = cart - previous
    item = {product: params[:product], style: params[:style], quantity: new_quantity}
    session[:cart] = cart + [item]
    render json: { message: "success", cart: session[:cart] }, :status => 200
  end
  
  def create_user_product
    if current_user.nil?
      @currency = 'usd'
    else
      @currency = current_user.currency
    end
    @order = OrderDetail.create(:first_name => session[:first_name] , :last_name => session[:last_name] , :zip_code => session[:zip_code] , :city => session[:city], :country => session[:country] , :additional_information => session[:additional_information] , :phone_number => session[:phone_number])
    session[:cart].each do |y|
      if y["style"].nil?
          @transaction = UserProduct.create(:user_id => current_user.id , :product_id => Product.find_by(:name => y["product"]).id , :quantity => y["quantity"] , :subtotal => y["quantity"]*Product.find_by(:name => y["product"]).product_prices.find_by(:currency => @currency).price , :order_detail_id => @order.id)
      else
          @transaction = UserProduct.create(:user_id => current_user.id , :product_id => Product.find_by(:name => y["product"]).id , :style_id => Style.find_by(:name => y["style"]).id , :quantity => y["quantity"] , :subtotal => y["quantity"]*Product.find_by(:name => y["product"]).product_prices.find_by(:currency => @currency).price , :order_detail_id => @order.id)
      end
    end
    session[:cart] = nil
    session[:total] = nil
    session[:first_name] = nil
    session[:last_name] = nil
    session[:zip_code] = nil
    session[:city] = nil
    session[:country] = nil
    session[:additional_information] = nil
    session[:phone_number] = nil
    # redirect_to  products_path
  end
  
  def cart
    @total_cost = session[:total]
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.sources.create(source: params[:stripeToken])
    charge = Stripe::Charge.create(
      :customer    => customer,
      :amount      => @total_cost*100,
      :currency    => current_user.currency
    )
    if charge["paid"]
      create_user_product
      redirect_to  products_path 
      # flash[:notice] = 'Card charged successfully.'
    else
      # rescue Stripe::CardError => e
      #   flash[:error] = e
      redirect_to  products_checkout_path
    end

  end

 def checkout
    @total_cost = session[:total]
    @payment = Payment.new({
      :intent =>  "sale",

      # ###Payer
      # A resource representing a Payer that funds a payment
      # Payment Method as 'paypal'
      :payer =>  {
        :payment_method =>  "paypal" },

      # ###Redirect URLs
      :redirect_urls => {
        :return_url => "#{request.base_url}/execute",
        :cancel_url => "#{request.base_url}/" },

      # ###Transaction
      # A transaction defines the contract of a
      # payment - what is the payment for and who
      # is fulfilling it.
      :transactions =>  [{

        # Item List
        # :item_list => {
        #   :items => [{
        #     :name => "item",
        #     :sku => "item",
        #     :price => "5",
        #     :currency => "USD",
        #     :quantity => 1 }]},

        # ###Amount
        # Let's you specify a payment amount.
        :amount =>  {
          :total =>  @total_cost ,
          :currency =>  current_user.currency.upcase },
        :description =>  "This is the payment transaction description." }]})
    # Create Payment and return status
    if @payment.create
      render json: {success: true, paymentID: @payment.id}
    else
      render json: {success: false}
    end
  end

  def execute
    payment = PayPal::SDK::REST::Payment.find(params[:paymentID])
    if payment.execute(payer_id: params[:payerID])
      create_user_product
      render json: {msg: 'Payment Complete'}
      # redirect_to  products_path(format: :json , msg: 'Payment Complete')
    else
      render json: {msg: payment.error}
    end
  end

  def remove_item
    session[:cart].delete_at(params[:id].to_i)
    redirect_to products_checkout_path 
  end
  def address
    session[:first_name] = params[:first_name]
    session[:last_name] = params[:last_name]
    session[:zip_code] = params[:zip_code]
    session[:city] = params[:city]
    session[:country] = params[:country]
    session[:additional_information] = params[:additional_information]
    session[:phone_number] = params[:phone_number]
    redirect_to products_checkout_path
  end
  def sofort_pay
    @total_cost = session[:total]
    if current_user.currency.upcase == "EUR"
      client = Sofort::Client.new
      payment = client.pay(@total_cost, params[:name] , { success_url: "http://localhost:3000/sofort_check" , abort_url: 'https://google.com' , language_code: current_user.locale , currency_code: current_user.currency.upcase , country_code: current_user.country.upcase})
      session[:payment] = payment["transaction"]
      redirect_to payment["payment_url"]
    else
      flash[:notice] =  'Please choose currency to be Euro , Sofort accepts only Euro'
    end
  end
  def sofort_check
    client = Sofort::Client.new
    transaction = client.details(session[:payment])
    if transaction["transaction"].nil?
      render json: {msg: 'Payment Failed'}
    else
      create_user_product
      flash[:notice] = 'Payment Complete'
      redirect_to products_path
    end
    
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/cart-2.html.erb
<!DOCTYPE html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://www.paypalobjects.com/api/checkout.js"></script>
</head>
<body>
<div class="nav-cover">
</div>

<div class="cart container">
  <div class="row">
    <div class="col-sm-12 col-sm-push-1">
      <h1>CART</h1>

      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default panel-cart">
          <div class="panel-header" role="tab" id="headingOne">
            <h4 class="panel-title title-panel">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <div class="clearfix">
                      <span class="cart-arrow pull-left">
                        <%= image_tag('True.svg') %>
                       <h3 class="cart-title pull-right pull-right-text">1. Please Add Your Address</h3>
                      </span>
                </div>
              </a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
              <div class="cart-adress">
                <% if session[:first_name].blank? %>
                  <div data-toggle="modal" data-target="#exampleModal" class="address-right">
                    <a><%= image_tag('add-your-adress .svg') %></a>
                  </div>
                <% else %>
                  <h3>First Name :</h3> <%= session[:first_name] %>
                  <h3>Last Name :</h3> <%= session[:last_name] %>
                  <h3>Zip Code :</h3> <%= session[:zip_code] %>
                  <h3>City :</h3> <%= session[:city] %>
                  <h3>Country :</h3> <%= session[:country] %>
                  <h3>Additional Information :</h3> <%= session[:additional_information] %>
                  <h3>Phone Number :</h3> <%= session[:phone_number] %>
                <% end %>
                <div class="cart-form">
                  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close cart-close-form" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title" id="exampleModalLabel">Add Your New Address</h4>
                        </div>
                        <div class="modal-body">
                          <%= form_tag products_address_path do %>
                            <div class="form-group">
                              <label for="message-text" class="control-label">First Name</label>
                              <%= text_field_tag :first_name, nil, class: 'form-control', id: "recipient-name" %>

                            </div>
                            <div class="form-group">
                              <label for="message-text" class="control-label">Last Name</label>

                              <%= text_field_tag :last_name, nil, class: 'form-control', id: "recipient-name" %>

                            </div>
                            <div class="form-group">
                              <label for="message-text" class="control-label">Zip Code</label>
                              <%= text_field_tag :zip_code, nil, class: 'form-control', id: "recipient-name" %>

                            </div>
                            <div class="form-group">
                              <label for="message-text" class="control-label">City</label>
                              <%= text_field_tag :city, nil, class: 'form-control', id: "recipient-name" %>

                            </div>
                            <div class="form-group">
                              <label for="message-text" class="control-label">Country</label>
                              <%= text_field_tag :country, nil, class: 'form-control', id: "recipient-name" %>

                            </div>
                            <div class="form-group">
                              <label for="message-text" class="control-label">Additional Information</label>

                              <%= text_field_tag :additional_information, nil, class: 'form-control additional-height', id: "recipient-name" %>

                            </div>
                            <div class="form-group">
                              <label for="message-text" class="control-label">Phone Number</label>
                              <%= text_field_tag :phone_number, nil, class: 'form-control', id: "recipient-name" %>

                            </div>
                            <%= submit_tag "Save", class: "btn btn-primary cart-sending-message" %>
                          <% end %>

                        </div>
                        <!-- <div class="modal-footer">
                          <button type="button" class="btn btn-primary cart-sending-message">Send message</button>
                        </div> -->
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>

          <div class="panel panel-default panel-cart">
            <div class="panel-header" role="tab" id="headingTwo">
              <h4 class="panel-title title-panel">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  <div class="clearfix">
          <span class="cart-arrow pull-left">
           <h3 class="cart-title pull-right pull-right-text">2. ORDER SUMMARY</h3>
            <%= image_tag('True.svg') %>
            </span>
                  </div>
                </a>
              </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
              <div class="panel-body">

                <div class="cart-adress">
                  <div class="panel-body">
                    <table class="table">
                      <thead>
                      <tr>
                        <th>&nbsp;</th>
                        <th>Item</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Subtotal</th>
                        <th>Options</th>
                      </tr>
                      </thead>
                      <tbody>
                      <% session[:cart].each_with_index do |ci, index| %>
                        <tr class="cart-item">
                          <td class="img">
                            <%= ci['style'].present? ? image_tag("products/#{ci['style']}.png") : image_tag("products/#{ci['product']}.svg") %>
                          </td>
                          <td>
                            <strong>The <%= ci['style'].try :titleize %> Smile</strong><br>
                            <%= Style.find_by(name: ci['style']).try :tagline %>
                          </td>
                          <td><%= ci['quantity'].to_i %></td>
                          <td><%= number_to_currency(Product.find_by(name: ci['product']).product_prices.find_by(:currency => @currency).price) %> </td>
                          <td><%= number_to_currency(Product.find_by(name: ci['product']).product_prices.find_by(:currency => @currency).price * ci['quantity'].to_i) %></td>
                          <td><%= link_to "Remove", delete_item_path(index), method: :delete %></td>
                        </tr>
                      <% end %>
                      </tbody>
                    </table>

                  </div>
                </div>

              </div>
            </div>
          </div>
          <div class="panel panel-default panel-cart">
            <div class="panel-header" role="tab" id="headingThree">
              <h4 class="panel-title  title-panel">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                  <div class="clearfix">
                      <span class="cart-arrow pull-left">
                        <h3 class="cart-title pull-right pull-right-text">3. PAYMENT METHOD</h3>
                        <%= image_tag('True.svg') %>
                      </span>
                  </div>
                </a>
              </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
              <div class="panel-body">

                <div class="cart-adress">

                  <div class="col-md-8 col-xs-12 col-sm-push-2 payment-items">
                    <div class="col-md-12 col-sm-8 col-xs-12 shadow product-steps-item steps-slogan-left" style="margin-bottom: 1em">
                      <div class="cell choose-product" style="height: 100px">
                        <div class="col-md-4 col-sm-4" style="margin: 0">
                          <label class="container">Paypal
                            <span class="checkmark"></span>
                          </label>
                        </div>
                        <div class="col-md-8 col-sm-8 product-text">
                          <div class="choose-heading">
                            <div id="paypal-button-container"></div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="col-md-12 col-sm-8 col-xs-12 shadow product-steps-item steps-slogan-left" style="margin-bottom: 1em">
                      <div class="cell choose-product" style="height: 100px">
                        <div class="col-md-4 col-sm-4" style="margin: 0">
                          <label class="container">Bank transfer
                            <span class="checkmark"></span>
                          </label>
                        </div>
                        <div class="col-md-8 col-sm-8 product-text">
                          <div class="choose-heading"><%= image_tag('sofort.svg') %></div><%= form_tag products_sofort_path do %>
                            <div class="form-group">
                              <label for="message-text" class="control-label">Name</label>
                              <%= text_field_tag :name, nil %>
                              <% if notice %>
                                <p><%= notice %></p>
                              <% end %>
                            </div>
                            <%= submit_tag "Submit" %>
                          <% end %>
                        </div>
                      </div>
                    </div>

                    <div class="col-md-12 col-sm-8 col-xs-12 shadow product-steps-item steps-slogan-left" style="margin-bottom: 1em">
                      <div class="cell choose-product" style="height: 100px">
                        <div class="col-md-4 col-sm-4" style="margin: 0">
                          <label class="container">Credit card
                            <span class=""></span>
                          </label>

                          <%= form_tag products_checkout_path do %>
                            <article>
                              <% if flash[:error].present? %>
                                <div id="error_explanation">
                                  <p><%= flash[:error] %></p>
                                </div>
                              <% end %>
                              <label class="amount">
                                <!-- <span>Amount:
                                <% number_to_currency(@total_cost) %></span> -->
                              </label>
                            </article>

                            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                                    data-description="SmileUp Payment"
                                    data-amount=
                                      <% @total_cost %>
                                        data-locale="auto"></script>
                          <% end %>
                        </div>
                        <divclass
                        ="col-md-8 col-sm-8 product-text">
                        <div class="choose-heading"><%= image_tag('visaandmaster.svg') %></div>
                      </div>
                    </div>
                  </div>

                </div>

              </div>

            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
  <!-- payment form -->


  <!-- If you're using Stripe for payments -->

</div>
</div>
</body>

app/views/cart/index.html.erb
<div class="nav-cover">
</div>

<div class="cart container">
  <div class="row">
    <div class="col-sm-10 col-sm-push-1">
      <h1>CART</h1>
      <div class="panel panel-default shadow">
        <div class="panel-heading">&nbsp;</div>
          <div class="panel-body">
            <% if @cart.count == 0 %>
              <strong>No items in cart yet!</strong>
            <% else %>
              <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>&nbsp;</th>
                    <th>Item</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Subtotal</th>
                  </tr>
                </thead>
                <tbody>
                  <% @cart.each do |ci| %>
                  <tr class="cart-item">
                    <td class="img">

                      <%=  ci['style'].present? ? image_tag("products/#{ci['style']}.png") : image_tag("products/#{ci['product']}.svg")%>
                    </td>
                    <td>
                      <strong>The <%= ci['style'].try :titleize %> Smile</strong><br>
                      <%= Style.find_by(name: ci['style']).try :tagline %>
                    </td>
                    <td><%= ci['quantity'].to_i %></td>
                    <td><%= number_to_currency(Product.find_by(name: ci['product']).product_prices.find_by(:currency => current_user.currency).price ) %> </td>
                    <td><%= number_to_currency(Product.find_by(name: ci['product']).product_prices.find_by(:currency => current_user.currency).price * ci['quantity'].to_i) %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
              <div class="subtotal clearfix">
                <h2 class="pull-left">TOTAL: <%= number_to_currency(@total) %></h2>
                <a class="btn btn-green btn-lg pull-right" href="/products/checkout" role="button">CONTINUE TO CHECKOUT</a>
                
              </div>
            <% end %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>